### ISSUE TITLE
手机屏幕关闭后，计时会停止

### ISSUE THREAD

**Issue by lmk123** [lmk123/Runner#2]
当手机屏幕关闭几秒之后，`setTimeout` 这类的函数会停止执行。唯一能解决这个问题的办法就是使用**黑科技**防止手机屏幕自动关闭：[richtr/NoSleep.js](https://github.com/richtr/NoSleep.js)

最好自己 fork 之后修改一下源码，使它支持 UMD、将它发布到 npm，并解决[最新 iOS 系统下的问题](https://github.com/richtr/NoSleep.js/issues/12)

**Comment by lmk123** [comment]
黑科技试验失败。。

看来只能辛苦下大拇指了

**Comment by ghost** [comment]
关于阻止屏幕自动睡眠：
Android可以通过循环播放很短(比如1s)的视频做到(这个方法不知在iOS有没有用)，iOS据说是用定时器函数吧。

关于检测锁屏事件：
可以通过Page Visitable API实现，Android 6.0.1 Chrome和Firefox测试通过，iOS7 safari chrome都不行，不知其他iOS版本是否可行。

**Comment by lmk123** [comment]
@iVanilla 在新版本的 Runner 中我使用了另外一种方法来使计时器锁屏后再开启也能准确显示，但这样仍然没法做到后台通知。。web 目前还是很难跳出浏览器的限制。

**Comment by ghost** [comment]
@lmk123 嗯，我问这个是因为我在做一个H5游戏。
